/*
These enumerations are potentially an unstable binary interface.
For safer access, consider fetching their values with MinaModAPI::GetEnum
*/

#define YC_KEY_BACKSPACE 0
#define YC_KEY_TAB 1
#define YC_KEY_CLEAR 2
#define YC_KEY_RETURN 3
#define YC_KEY_PAUSE 4
#define YC_KEY_ESCAPE 5
#define YC_KEY_SPACE 6
#define YC_KEY_EXCLAIM 7
#define YC_KEY_QUOTEDBL 8
#define YC_KEY_HASH 9
#define YC_KEY_DOLLAR 10
#define YC_KEY_AMPERSAND 11
#define YC_KEY_QUOTE 12
#define YC_KEY_LEFTPAREN 13
#define YC_KEY_RIGHTPAREN 14
#define YC_KEY_ASTERISK 15
#define YC_KEY_PLUS 16
#define YC_KEY_COMMA 17
#define YC_KEY_MINUS 18
#define YC_KEY_PERIOD 19
#define YC_KEY_SLASH 20
#define YC_KEY_0 21
#define YC_KEY_1 22
#define YC_KEY_2 23
#define YC_KEY_3 24
#define YC_KEY_4 25
#define YC_KEY_5 26
#define YC_KEY_6 27
#define YC_KEY_7 28
#define YC_KEY_8 29
#define YC_KEY_9 30
#define YC_KEY_COLON 31
#define YC_KEY_SEMICOLON 32
#define YC_KEY_LESS 33
#define YC_KEY_EQUALS 34
#define YC_KEY_GREATER 35
#define YC_KEY_QUESTION 36
#define YC_KEY_AT 37
#define YC_KEY_LEFTBRACKET 38
#define YC_KEY_BACKSLASH 39
#define YC_KEY_RIGHTBRACKET 40
#define YC_KEY_CARET 41
#define YC_KEY_UNDERSCOR 42
#define YC_KEY_BACKQUOTE 43
#define YC_KEY_A 44
#define YC_KEY_B 45
#define YC_KEY_C 46
#define YC_KEY_D 47
#define YC_KEY_E 48
#define YC_KEY_F 49
#define YC_KEY_G 50
#define YC_KEY_H 51
#define YC_KEY_I 52
#define YC_KEY_J 53
#define YC_KEY_K 54
#define YC_KEY_L 55
#define YC_KEY_M 56
#define YC_KEY_N 57
#define YC_KEY_O 58
#define YC_KEY_P 59
#define YC_KEY_Q 60
#define YC_KEY_R 61
#define YC_KEY_S 62
#define YC_KEY_T 63
#define YC_KEY_U 64
#define YC_KEY_V 65
#define YC_KEY_W 66
#define YC_KEY_X 67
#define YC_KEY_Y 68
#define YC_KEY_Z 69
#define YC_KEY_DELETE 70
#define YC_KEY_KP0 71
#define YC_KEY_KP1 72
#define YC_KEY_KP2 73
#define YC_KEY_KP3 74
#define YC_KEY_KP4 75
#define YC_KEY_KP5 76
#define YC_KEY_KP6 77
#define YC_KEY_KP7 78
#define YC_KEY_KP8 79
#define YC_KEY_KP9 80
#define YC_KEY_KP_PERIOD 81
#define YC_KEY_KP_DIVIDE 82
#define YC_KEY_KP_MULTIPLY 83
#define YC_KEY_KP_MINUS 84
#define YC_KEY_KP_PLUS 85
#define YC_KEY_KP_ENTER 86
#define YC_KEY_KP_EQUALS 87
#define YC_KEY_UP 88
#define YC_KEY_DOWN 89
#define YC_KEY_RIGHT 90
#define YC_KEY_LEFT 91
#define YC_KEY_INSERT 92
#define YC_KEY_HOME 93
#define YC_KEY_END 94
#define YC_KEY_PAGEUP 95
#define YC_KEY_PAGEDOWN 96
#define YC_KEY_F1 97
#define YC_KEY_F2 98
#define YC_KEY_F3 99
#define YC_KEY_F4 100
#define YC_KEY_F5 101
#define YC_KEY_F6 102
#define YC_KEY_F7 103
#define YC_KEY_F8 104
#define YC_KEY_F9 105
#define YC_KEY_F10 106
#define YC_KEY_F11 107
#define YC_KEY_F12 108
#define YC_KEY_F13 109
#define YC_KEY_F14 110
#define YC_KEY_F15 111
#define YC_KEY_NUMLOCK 112
#define YC_KEY_CAPSLOCK 113
#define YC_KEY_SCROLLLOCK 114
#define YC_KEY_RSHIFT 115
#define YC_KEY_LSHIFT 116
#define YC_KEY_RCTRL 117
#define YC_KEY_LCTRL 118
#define YC_KEY_RALT 119
#define YC_KEY_LALT 120
#define YC_KEY_RMETA 121
#define YC_KEY_LMETA 122
#define YC_KEY_LSUPER 123
#define YC_KEY_RSUPER 124
#define YC_KEY_MODE 125
#define YC_KEY_COMPOSE 126
#define YC_KEY_HELP 127
#define YC_KEY_PRINT 128
#define YC_KEY_SYSREQ 129
#define YC_KEY_BREAK 130
#define YC_KEY_MENU 131
#define YC_KEY_SHIFT 132
#define YC_KEY_CTRL 133
#define YC_KEY_ALT 134
#define YC_KEY_SUPER 135
#define YC_KEY_META 136

#define YC_INPUT_DPAD_UP 0
#define YC_INPUT_DPAD_DOWN 1
#define YC_INPUT_DPAD_LEFT 2
#define YC_INPUT_DPAD_RIGHT 3
#define YC_INPUT_BPAD_UP 4
#define YC_INPUT_BPAD_DOWN 5
#define YC_INPUT_BPAD_LEFT 6
#define YC_INPUT_BPAD_RIGHT 7
#define YC_INPUT_L1 8
#define YC_INPUT_L2 9
#define YC_INPUT_L3 10
#define YC_INPUT_R1 11
#define YC_INPUT_R2 12
#define YC_INPUT_R3 13
#define YC_INPUT_START 14
#define YC_INPUT_SELECT 15
#define YC_INPUT_LSTICK 16
#define YC_INPUT_LSTICK_UP 17
#define YC_INPUT_LSTICK_DOWN 18
#define YC_INPUT_LSTICK_LEFT 19
#define YC_INPUT_LSTICK_RIGHT 20
#define YC_INPUT_RSTICK 21
#define YC_INPUT_RSTICK_UP 22
#define YC_INPUT_RSTICK_DOWN 23
#define YC_INPUT_RSTICK_LEFT 24
#define YC_INPUT_RSTICK_RIGHT 25
#define YC_INPUT_TOUCH1_1 26
#define YC_INPUT_TOUCH1_2 27
#define YC_INPUT_TOUCH1_3 28
#define YC_INPUT_TOUCH1_4 29
#define YC_INPUT_TOUCH1_5 30
#define YC_INPUT_TOUCH1_6 31
#define YC_INPUT_TOUCH1_7 32
#define YC_INPUT_TOUCH2_1 33
#define YC_INPUT_TOUCH2_2 34
#define YC_INPUT_TOUCH2_3 35
#define YC_INPUT_TOUCH2_4 36
#define YC_INPUT_TOUCH2_5 37
#define YC_INPUT_TOUCH3_1 38
#define YC_INPUT_TOUCH3_2 39
#define YC_INPUT_TOUCH3_3 40
#define YC_INPUT_TOUCH3_4 41
#define YC_INPUT_TOUCH3_5 42

#define GAMESTATE_DEVINIT 0
#define GAMESTATE_STARTUP 1
#define GAMESTATE_INTROBEACH 2
#define GAMESTATE_BAYOU 3
#define GAMESTATE_CRYPTA 4
#define GAMESTATE_CRYPTB 5
#define GAMESTATE_BONEBEACHA 6
#define GAMESTATE_BONEBEACHB 7
#define GAMESTATE_SEPTEMBURGA 8
#define GAMESTATE_SEPTEMBURGB 9
#define GAMESTATE_SEPTEMBURG_SEWER 10
#define GAMESTATE_FROZENTRAINYARDA 11
#define GAMESTATE_FROZENTRAINYARDB 12
#define GAMESTATE_FROZENTRAINYARDC 13
#define GAMESTATE_FROZENTRAINYARDBOSS 14
#define GAMESTATE_ASTRALORRERY 15
#define GAMESTATE_MANSION 16
#define GAMESTATE_HUB 17
#define GAMESTATE_HUB_OVERWORLD_EAST 18
#define GAMESTATE_HUB_OVERWORLD_WEST 19
#define GAMESTATE_HUB_OVERWORLD_SOUTH 20
#define GAMESTATE_HUB_MANSION 21
#define GAMESTATE_ASTRAL_ORRERY_MIRROR_HUB 22
#define GAMESTATE_HUB_BAYOU_OVERWORLD 23
#define GAMESTATE_FISHING_HOLE 24
#define GAMESTATE_CRYPT_OVERWORLD 25
#define GAMESTATE_CRYPT_OVERWORLD_HELL 26
#define GAMESTATE_BONEBEACH_OVERWORLD 27
#define GAMESTATE_SEPTEMBURG_OVERWORLD 28
#define GAMESTATE_CHECKPOINTROOM 29
#define GAMESTATE_WEAPONGET_WORLD 30
#define GAMESTATE_RANDOM_ENCOUNTER 31
#define GAMESTATE_INTROSEA 32
#define GAMESTATE_MANSIONORPHANAGE 33
#define GAMESTATE_PUPPETMASTER 34
#define GAMESTATE_EVRAARENA 35
#define GAMESTATE_INTROBEACH_SCRATCH 36
#define GAMESTATE_BAYOU_SCRATCH 37
#define GAMESTATE_CRYPT_SCRATCH 38
#define GAMESTATE_SEPTEMBURG_SCRATCH 39
#define GAMESTATE_BONEBEACH_SCRATCH 40
#define GAMESTATE_FROZENTRAINYARD_SCRATCH 41
#define GAMESTATE_ASTRALORRERY_SCRATCH 42
#define GAMESTATE_MANSION_SCRATCH 43
#define GAMESTATE_CRYPT_TOWER 44
#define GAMESTATE_BAYOU_TOWER 45
#define GAMESTATE_SEPTEMBURG_TOWER 46
#define GAMESTATE_BONEBEACH_TOWER 47
#define GAMESTATE_FROZENTRAINYARD_TOWER 48
#define GAMESTATE_ASTRAL_TOWER 49
#define GAMESTATE_MANSION_TOWER 50
#define GAMESTATE_TRAINCABIN 51
#define GAMESTATE_TRAINCABIN_OVERLAY_BAYOU 52
#define GAMESTATE_TRAINCABIN_OVERLAY_BONEBEACH 53
#define GAMESTATE_TRAINCABIN_OVERLAY_FROZEN 54
#define GAMESTATE_TRAINCABIN_OVERLAY_HUB 55
#define GAMESTATE_TRAINCABIN_OVERLAY_SEPTEMBURG 56
#define GAMESTATE_GYM_ALEC 57
#define GAMESTATE_GYM_BRIDGET 58
#define GAMESTATE_GYM_DANDY 59
#define GAMESTATE_GYM_ELI 60
#define GAMESTATE_GYM_ERIC 61
#define GAMESTATE_GYM_SANDY 62
#define GAMESTATE_GYM_SEAN 63
#define GAMESTATE_GYM_IAN 64
#define GAMESTATE_GYM_IANG 65
#define GAMESTATE_GYM_ADAM 66
#define GAMESTATE_GYM_CHARLIE 67
#define GAMESTATE_GYM_BONEBEACH 68
#define GAMESTATE_GYM_CHECKPOINTROOM_ALT 69
#define GAMESTATE_GYM_COMBAT 70
#define GAMESTATE_GYM_FERRO_FLUID 71
#define GAMESTATE_GYM_GLASS 72
#define GAMESTATE_GYM_GRINDRAIL 73
#define GAMESTATE_GYM_INTERACTIONS 74
#define GAMESTATE_GYM_PORTRAIT_ENEMY 75
#define GAMESTATE_GYM_RAINBOW_PLATFORM 76
#define GAMESTATE_GYM_SURPRISE_SPAWN 77
#define GAMESTATE_GYM_TILESETTEST 78
#define GAMESTATE_GYM_TOWERCLIMB 79
#define GAMESTATE_GYM_TRAILERLAND 80
#define GAMESTATE_GYM_TRAILERLANDVISTA 81
#define GAMESTATE_GYM_WORLDLOADTEST1 82
#define GAMESTATE_GYM_WORLDLOADTEST2 83
#define GAMESTATE_TITLE_SCREEN 84
#define GAMESTATE_YCG_LOGO 85
#define GAMESTATE_TRINKETS 86
#define GAMESTATE_GEAR 87
#define GAMESTATE_DEATH 88
#define GAMESTATE_BONESTONEMACHINE 89
#define GAMESTATE_WEAPONS_CHEST 90
#define GAMESTATE_WORLD_MAP 91
#define GAMESTATE_NEWSPAPER_DISPLAY 92
#define GAMESTATE_NEWSPAPER_SELECT 93
#define GAMESTATE_FISH_SELECT 94
#define GAMESTATE_MANUAL 95
#define GAMESTATE_DEMO_ACTIVATE 96
#define GAMESTATE_DEMO_SELECT 97
#define GAMESTATE_DEMO_RESULTS 98
#define GAMESTATE_DEMO_UPSELL 99
#define GAMESTATE_DEMO_KICKSTARTER 100
#define GAMESTATE_OPTIONS_MENU 101
#define GAMESTATE_FEATS_MENU 102
#define GAMESTATE_BRIGHTNESS_MENU 103
#define GAMESTATE_SCREENSCALE_MENU 104
#define GAMESTATE_PROFILE_SELECT_MENU 105
#define GAMESTATE_CREDITS_MENU 106
#define GAMESTATE_SOUND_TEST_MENU 107
#define GAMESTATE_CHEATS_MENU 108
#define GAMESTATE_PANORAMA_INTROLETTER 109
#define GAMESTATE_PANORAMA_HUB 110
#define GAMESTATE_PANORAMA_BAYOU 111
#define GAMESTATE_PANORAMA_CRYPT 112
#define GAMESTATE_PANORAMA_SEPTEMBURG 113
#define GAMESTATE_PANORAMA_BONEBEACH 114
#define GAMESTATE_PANORAMA_ASTRALORRERY 115
#define GAMESTATE_PANORAMA_FROZENTRAINYARD 116
#define GAMESTATE_PANORAMA_WINDOWFALL 117
#define GAMESTATE_PANORAMA_MANSION 118
#define GAMESTATE_PANORAMA_ENDING_START 119
#define GAMESTATE_PANORAMA_ENDING_END 120
#define GAMESTATE_BIGART_BONEBEACHMAP 121
#define GAMESTATE_BIGART_CRYPTHEADSTONE 122
#define GAMESTATE_BIGART_MANSIONPRTGOOD 123
#define GAMESTATE_BIGART_MANSIONPRTEVIL 124
#define GAMESTATE_BIGART_MANSIONPORTRAIT 125
#define GAMESTATE_BIGART_SEPTCHALKBOARD 126
#define GAMESTATE_BIGART_SCROLLTEST 127
#define GAMESTATE_BIGART_MIRROR 128
#define GAMESTATE_BIGART_WINDOWPUSHPHOTO 129
#define GAMESTATE_BIGART_GIRAFFETINY 130
#define GAMESTATE_BIGART_TELESCOPE 131
#define GAMESTATE_BIGART_CATGHOSTS 132
#define GAMESTATE_BIGART_MANSIONPAINTING 133
#define GAMESTATE_INTRO_CINEMA_SCENE1 134
#define GAMESTATE_INTRO_CINEMA_SCENE2 135
#define GAMESTATE_INTRO_CINEMA_SCENE3A 136
#define GAMESTATE_INTRO_CINEMA_SCENE3B 137
#define GAMESTATE_INTRO_CINEMA_SCENE4 138
#define GAMESTATE_INTRO_CINEMA_SCENE5A 139
#define GAMESTATE_INTRO_CINEMA_SCENE5B 140
#define GAMESTATE_INTRO_CINEMA_SCENE5C 141
#define GAMESTATE_INTRO_CINEMA_SCENE6A 142
#define GAMESTATE_INTRO_CINEMA_SCENE6B 143
#define GAMESTATE_INTRO_CINEMA_SCENE7 144
#define GAMESTATE_ENDING_CINEMA_OSSEX 145
#define GAMESTATE_ENDING_CINEMA_CRYPT 146
#define GAMESTATE_ENDING_CINEMA_BAYOU 147
#define GAMESTATE_ENDING_CINEMA_BONEBEACH 148
#define GAMESTATE_ENDING_CINEMA_HOLLOWER 149
#define GAMESTATE_ENDING_CINEMA_SEPTEMBURG 150
#define GAMESTATE_ENDING_CINEMA_FROZEN 151
#define GAMESTATE_ENDING_CINEMA_ASTRAL 152
#define GAMESTATE_ENDING_CINEMA_MANSION 153
#define GAMESTATE_ENDING_PRECREDITS 154
#define GAMESTATE_ENDING_POSTCREDITS 155
#define GAMESTATE_TEXTDISPLAY 156

#define kItemType_None 0
#define kItemType_Shop_Exit 1
#define kItemType_Whip 2
#define kItemType_Whip_Level_2 3
#define kItemType_Whip_Level_3 4
#define kItemType_Hammer 5
#define kItemType_Hammer_Level_2 6
#define kItemType_Hammer_Level_3 7
#define kItemType_Daggers 8
#define kItemType_Daggers_Level_2 9
#define kItemType_Daggers_Level_3 10
#define kItemType_BusterBat 11
#define kItemType_BusterBat_Level_2 12
#define kItemType_BusterBat_Level_3 13
#define kItemType_Shield 14
#define kItemType_Shield_Level_2 15
#define kItemType_Shield_Level_3 16
#define kItemType_HealingVial 17
#define kItemType_HealingVialFirst 18
#define kItemType_HealingVialPickup 19
#define kItemType_HealingVialPackPickup 20
#define kItemType_ThrowingAxe 21
#define kItemType_ThrowingKnife 22
#define kItemType_WarpPortal 23
#define kItemType_ChargeLantern 24
#define kItemType_ShieldBash 25
#define kItemType_ChemicalClackers 26
#define kItemType_Bicycle 27
#define kItemType_HollowersRocks 28
#define kItemType_FogThrower 29
#define kItemType_LeashedPhantom 30
#define kItemType_MistShift 31
#define kItemType_HauntedUrn 32
#define kItemType_BarrierParasol 33
#define kItemType_FishingRod 34
#define kItemType_HealthRecovery 35
#define kItemType_FishHealthRecovery 36
#define kItemType_Magic_Small 37
#define kItemType_Magic_Medium 38
#define kItemType_Magic_Large 39
#define kItemType_Treasure_Smallest 40
#define kItemType_Treasure_Small 41
#define kItemType_Treasure_Medium 42
#define kItemType_Treasure_Large 43
#define kItemType_Treasure_Largest 44
#define kItemType_Treasure_Boss 45
#define kItemType_Treasure_GoldLarge 46
#define kItemType_Treasure_GoldLargest 47
#define kItemType_Treasure_JewelLarge 48
#define kItemType_Treasure_JewelLargest 49
#define kItemType_BoneDust 50
#define kItemType_Bonestone 51
#define kItemType_Bonestone_01 52
#define kItemType_Bonestone_02 53
#define kItemType_Bonestone_03 54
#define kItemType_Bonestone_04 55
#define kItemType_Bonestone_05 56
#define kItemType_Bonestone_06 57
#define kItemType_Bonestone_07 58
#define kItemType_Bonestone_08 59
#define kItemType_Bonestone_09 60
#define kItemType_Bonestone_10 61
#define kItemType_Bonestone_Tower 62
#define kItemType_Key 63
#define kItemType_Lock 64
#define kItemType_EarlyNote 65
#define kItemType_Note 66
#define kItemType_Trinket 67
#define kItemType_Magic_Upgrade 68
#define kItemType_Health_Upgrade 69
#define kItemType_Spark_Upgrade 70
#define kItemType_Vial_Upgrade 71
#define kItemType_Trinket_Upgrade 72
#define kItemType_Spark 73
#define kItemType_Upgrade_CandleVision 74
#define kItemType_Upgrade_WorldMap 75
#define kItemType_Upgrade_EnhancedMap 76
#define kItemType_Upgrade_RadarMap 77
#define kItemType_Upgrade_TwoSidearms 78
#define kItemType_ArmorUpgrade_Health 79
#define kItemType_ArmorUpgrade_Damage 80
#define kItemType_ArmorUpgrade_Custom 81
#define kItemType_Upgrade_JouleAlembic 82
#define kItemType_Upgrade_SidearmSaver 83
#define kItemType_Upgrade_SidearmKeeper 84
#define kItemType_Upgrade_TrainingDummy 85
#define kItemType_Upgrade_Phonograph 86
#define kItemType_Upgrade_FishingRod 87
#define kItemType_Upgrade_FishingUpgrade 88
#define kItemType_Upgrade_FishingGold 89
#define kItemType_Upgrade_WeirdDanceHUD 90
#define kItemType_Upgrade_TwoSidearmsHUD 91
#define kItemType_Armor_Default 92
#define kItemType_ArmorUpgrade_All 93
#define kItemType_Ticket_Pass 94
#define kItemType_Ticket_HUB 95
#define kItemType_Ticket_Bayou 96
#define kItemType_Ticket_Septemburg 97
#define kItemType_Ticket_BoneBeach 98
#define kItemType_Ticket_FrozenTrainyard 99
#define kItemType_Ticket_Exit 100
#define kItemType_Ticket_Unavailable 101
#define kItemType_Upgrade_FishingUpgradePickup 102
#define kItemType_Upgrade_FishingGoldPickup 103
#define kItemType_Fish_Ghost 104
#define kItemType_Fish_Puffer 105
#define kItemType_Fish_Flag 106
#define kItemType_Fish_Crumble 107
#define kItemType_Fish_Spincer 108
#define kItemType_Fish_Ice 109
#define kItemType_Fish_Trigger 110
#define kItemType_Fish_Glomper 111
#define kItemType_Fish_Goremaw 112
#define kItemType_Fish_Dork 113
#define kItemType_Fish_Eel 114
#define kItemType_Fish_Gazeworm 115
#define kItemType_Fish_Cuddlepus 116
#define kItemType_Fish_Trunkstar 117
#define kItemType_Fish_Shrimpster 118
#define kItemType_Fish_Boss 119
#define kItemType_Underlab_Default 120
#define kItemType_Underlab_Crypt 121
#define kItemType_Underlab_Bayou 122
#define kItemType_Underlab_Septemburg 123
#define kItemType_Underlab_Trainyard 124
#define kItemType_Underlab_BoneBeach 125
#define kItemType_Underlab_Astral 126
#define kItemType_Underlab_Mansion 127
#define kItemType_Underlab_HUB 128
#define kItemType_Underlab_East 129
#define kItemType_Underlab_West 130
#define kItemType_Underlab_South 131
#define kItemType_Underlab_Sewer 132
#define kItemType_Underlab_Guild 133
#define kItemType_Trinket_LaceGlove 134
#define kItemType_Trinket_TwilWeave 135
#define kItemType_Trinket_Salts 136
#define kItemType_Trinket_BriskBrew 137
#define kItemType_Trinket_BurrowPulse 138
#define kItemType_Trinket_PlasmaFunnel 139
#define kItemType_Trinket_BoneReleaser 140
#define kItemType_Trinket_SteadySoles 141
#define kItemType_Trinket_PlasmaSaver 142
#define kItemType_Trinket_BoneSaver 143
#define kItemType_Trinket_WispRage 144
#define kItemType_Trinket_WispHeal 145
#define kItemType_Trinket_FWisp 146
#define kItemType_Trinket_Windfall 147
#define kItemType_Trinket_ComboCapacitor 148
#define kItemType_Trinket_TractionTreads 149
#define kItemType_Trinket_BloodpressureBonnet 150
#define kItemType_Trinket_BoneMagnet 151
#define kItemType_Trinket_PutridClump 152
#define kItemType_Trinket_ProtoSpark 153
#define kItemType_Trinket_VialPouch 154
#define kItemType_Trinket_FireRing 155
#define kItemType_Trinket_SparkOrb 156
#define kItemType_Trinket_TStone 157
#define kItemType_Trinket_VSyrup 158
#define kItemType_Trinket_CrashPad 159
#define kItemType_Trinket_IronLung 160
#define kItemType_Trinket_TumblingTutu 161
#define kItemType_Trinket_Jug 162
#define kItemType_Trinket_UraniumBracelet 163
#define kItemType_Trinket_Shield 164
#define kItemType_Trinket_ShockFlint 165
#define kItemType_Trinket_AutoVial 166
#define kItemType_Trinket_PocketTrebuchet 167
#define kItemType_Trinket_Beast1 168
#define kItemType_Trinket_Beast2 169
#define kItemType_Trinket_Beast3 170
#define kItemType_Trinket_Beast4 171
#define kItemType_Trinket_Beast5 172
#define kItemType_Trinket_Beast6 173
#define kItemType_Trinket_VialDecoy 174
#define kItemType_Trinket_Vanishing 175
#define kItemType_Trinket_BoneBonus 176
#define kItemType_Trinket_SpiderB 177
#define kItemType_Trinket_VialSalvo 178
#define kItemType_Trinket_DodgingPendulum 179
#define kItemType_Trinket_DoubleJump 180
#define kItemType_Trinket_WallowersGauntlets 181
#define kItemType_Trinket_OozingOrgan 182
#define kItemType_Trinket_LightningRing 183
#define kItemType_Trinket_MRoot 184
#define kItemType_Trinket_LightningGrip 185
#define kItemType_Trinket_Statue 186
#define kItemType_Trinket_NiterBelt 187
#define kItemType_Trinket_BellowsBustle 188
#define kItemType_Trinket_BurrowChainer 189
#define kItemType_Trinket_JouleSyringe 190
#define kItemType_Trinket_PolypLamp 191
#define kItemType_Trinket_ThermalPack 192
#define kItemType_Trinket_VialParry 193
#define kItemType_Trinket_PlasmaJug 194

#define kCheat_BigJump 0
#define kCheat_Autojump 1
#define kCheat_SpaceJump 2
#define kCheat_QuickWalk 3
#define kCheat_Sprint 4
#define kCheat_MoreHangTime 5
#define kCheat_QuickBurrow 6
#define kCheat_SprintBurrow 7
#define kCheat_BurrowChain 8
#define kCheat_InfBurrow 9
#define kCheat_JumpToLeaveBurrow 10
#define kCheat_BurrowInv 11
#define kCheat_PainfulBurrow 12
#define kCheat_RopeFast 13
#define kCheat_QuickRails 14
#define kCheat_FlipControls 15
#define kCheat_Belmondo 16
#define kCheat_Commando 17
#define kCheat_DumbThrow 18
#define kCheat_Hedgehog 19
#define kCheat_WalkOnSpikes 20
#define kCheat_WalkOnPits 21
#define kCheat_PitsNoDamage 22
#define kCheat_NoKillLine 23
#define kCheat_MoreInvTime 24
#define kCheat_LessInvTime 25
#define kCheat_InfHealth 26
#define kCheat_MoreDamageTaken 27
#define kCheat_MoreDamageTaken2 28
#define kCheat_LessDamageTaken 29
#define kCheat_LessDamageTaken2 30
#define kCheat_InstaKillPlayer 31
#define kCheat_InstaKillEnemy 32
#define kCheat_NoDamageHeal 33
#define kCheat_LessPlasma 34
#define kCheat_MorePlasma 35
#define kCheat_PlasmaHealth 36
#define kCheat_PlasmaHeal 37
#define kCheat_LessPlasmaRose 38
#define kCheat_NoPlasmaRose 39
#define kCheat_LessCheckpointHeal 40
#define kCheat_NoCheckpointHeal 41
#define kCheat_ChangeGameSpeed 42
#define kCheat_ChangeNPGameSpeed 43
#define kCheat_MoreCheckpoints 44
#define kCheat_BossCheckpoints 45
#define kCheat_FewerCheckpoints 46
#define kCheat_NoCheckpoints 47
#define kCheat_NoUnderlab 48
#define kCheat_InfVials 49
#define kCheat_QuickHeal 50
#define kCheat_BigKnockback 51
#define kCheat_QuickAttacks 52
#define kCheat_SparkAttackBoost 53
#define kCheat_EarlyWeapons 54
#define kCheat_AnyWeaponStarter 55
#define kCheat_DeloreanMode 56
#define kCheat_NoAggro 57
#define kCheat_ScaleCombat 58
#define kCheat_EnemyLevelMax 59
#define kCheat_BossWeak 60
#define kCheat_BossWeakest 61
#define kCheat_SuddenDeath 62
#define kCheat_IgnoreEnemies 63
#define kCheat_Meteor 64
#define kCheat_InfSidearm 65
#define kCheat_SidearmNoLimit 66
#define kCheat_SidearmCheap 67
#define kCheat_SidearmPricey 68
#define kCheat_SidearmDrop 69
#define kCheat_SidearmRandom 70
#define kCheat_SidearmFavorite 71
#define kCheat_SidearmRoulette 72
#define kCheat_SuperSidearms 73
#define kCheat_NoSidearms 74
#define kCheat_SidearmHealth 75
#define kCheat_SidearmDangerous 76
#define kCheat_PetMode 77
#define kCheat_NoTrinket 78
#define kCheat_SuperLightning 79
#define kCheat_SuperStolenoid 80
#define kCheat_SuperBellows 81
#define kCheat_SuperOozing 82
#define kCheat_SuperBrisk 83
#define kCheat_SuperSpider 84
#define kCheat_WeirdDance 85
#define kCheat_UnlimitedKeys 86
#define kCheat_FreeLocks 87
#define kCheat_TrainPass 88
#define kCheat_AllHealth 89
#define kCheat_AllVials 90
#define kCheat_AllMagic 91
#define kCheat_AllSparks 92
#define kCheat_AllTrinketUpgrades 93
#define kCheat_AllUpgrade 94
#define kCheat_AllWeapons 95
#define kCheat_AllArmors 96
#define kCheat_AllTrinkets 97
#define kCheat_AllTrinketsEquipped 98
#define kCheat_LevelingDeathOne 99
#define kCheat_LevelingDeath 100
#define kCheat_LevelingFast20 101
#define kCheat_LevelingFast50 102
#define kCheat_LevelingSlow20 103
#define kCheat_LevelingSlow50 104
#define kCheat_LevelingType 105
#define kCheat_LevelingNoCap 106
#define kCheat_NoBones 107
#define kCheat_BonesBouncy 108
#define kCheat_ExtraBones 109
#define kCheat_BossExtraBones 110
#define kCheat_DeathAllSparks 111
#define kCheat_DeathLose50P 112
#define kCheat_DeathLoseNone 113
#define kCheat_EnemyExtraBones 114
#define kCheat_ShopPrice 115
#define kCheat_NoGeneral 116
#define kCheat_NoMerchantWeapon 117
#define kCheat_NoMerchantTrinket 118
#define kCheat_NoPawnShop 119
#define kCheat_NoSandwich 120
#define kCheat_WarpHome 121
#define kCheat_StartRandomItem 122
#define kCheat_StartRandomWarp 123
#define kCheat_StartRandomSidearm 124
#define kCheat_StartRandomLevel 125
#define kCheat_StartNewGamePlus 126
#define kCheat_StartProgBoat 127
#define kCheat_StartProgIntro 128
#define kCheat_StartProgCrypt 129
#define kCheat_StartProgBayou 130
#define kCheat_StartProgSeptemburg 131
#define kCheat_StartProgBoneBeach 132
#define kCheat_StartProgFrozenTrainyard 133
#define kCheat_StartProgAstralOrrery 134
#define kCheat_StartProgMansion 135
#define kCheat_StartProgMiniBoss 136
#define kCheat_StartBonestone 137
#define kCheat_StartTrainPass 138
#define kCheat_StartTrainPassMax 139
#define kCheat_StartTrinketBeast 140
#define kCheat_StartTrinketWisp 141
#define kCheat_StartTrinketParkour 142
#define kCheat_StartTrinketLightning 143
#define kCheat_StartTrinketHeavy 144
#define kCheat_StartTrinketBurrow 145
#define kCheat_StartTrinketSpeed 146
#define kCheat_StartTrinketPits 147
#define kCheat_StartTrinketStolenoid 148
#define kCheat_StartLevel 149
#define kCheat_StartRandLevel 150
#define kCheat_StartHealthUpgrade 151
#define kCheat_StartHealthUpgradeMax 152
#define kCheat_StartTrinketUpgradeMax 153
#define kCheat_StartSparkUpgradeMax 154
#define kCheat_StartVialUpgrade 155
#define kCheat_StartVialUpgradeMax 156
#define kCheat_StartSidearmUpgrade 157
#define kCheat_StartArmorDamage 158
#define kCheat_StartArmorHealth 159
#define kCheat_StartArmorCustom 160
#define kCheat_StartCandleVision 161
#define kCheat_StartMap 162
#define kCheat_StartUnderlabSidearm 163
#define kCheat_StartUnderlabPhonograph 164
#define kCheat_StartUnderlabAll 165
#define kCheat_StartWhipUpgradeMax 166
#define kCheat_StartHammerUpgradeMax 167
#define kCheat_StartDaggerUpgradeMax 168
#define kCheat_StartBusterUpgradeMax 169
#define kCheat_StartShieldUpgradeMax 170
#define kCheat_StartWeaponsAvailable 171
#define kCheat_StartUpgradeAll 172
#define kCheat_QuickLocks 173
#define kCheat_FloorIsLava 174
#define kCheat_NoWind 175
#define kCheat_DarknessHelper 176
#define kCheat_NoDarkness 177
#define kCheat_MsHyde 178
#define kCheat_PrankBombs 179
#define kCheat_PrankCandles 180
#define kCheat_PrankSparkles 181
#define kCheat_PrankWisps 182
#define kCheat_DamageNo 183
#define kCheat_DamageNoPlayer 184
#define kCheat_GlobalPal 185
#define kCheat_CloakColor1 186
#define kCheat_CloakColor2 187
#define kCheat_CloakColor3 188
#define kCheat_IdleDance 189
#define kCheat_Giant 190
#define kCheat_Giant2 191
#define kCheat_GiantEnemies 192
#define kCheat_GiantEnemies2 193
#define kCheat_EnemyShakeCamera 194
#define kCheat_StartInvisible 195
#define kCheat_NoWeather 196
#define kCheat_NoHUD 197
#define kCheat_RandomMusic 198
#define kCheat_Weather 199
#define kCheat_Victorian 200
#define kCheat_Hieroglyph 201
#define kCheat_RotateCamera 202
#define kCheat_RotateCameraInput 203
#define kCheat_Mirror 204
#define kCheat_Upsidedown 205
#define kCheat_NYC 206
#define kCheat_TavernName 207
#define kCheat_TavernColor 208
#define kCheat_TavernTheme 209
#define kCheat_TavernMusic 210
#define kCheat_TavernGhost 211
#define kCheat_PortraitAccessory 212
#define kCheat_CustomFlower 213
#define kCheat_Easy 214
#define kCheat_Tour 215
#define kCheat_Harder 216
#define kCheat_SecondQuest 217
#define kCheat_Combo1 218
#define kCheat_Combo2 219
#define kCheat_Combo3 220
#define kCheat_ComboQuickAll 221
#define kCheat_ComboBeast 222
#define kCheat_ComboProgUpgrade 223
#define kCheat_ComboWeapon1 224
#define kCheat_ComboWeapon2 225
#define kCheat_ComboWeapon3 226
#define kCheat_ComboWeapon4 227
#define kCheat_ComboWeapon5 228
#define kCheat_ComboSneaky 229
#define kCheat_ComboPitHelp 230
#define kCheat_ComboChallenge1 231
#define kCheat_ComboChallenge2 232
#define kCheat_ComboChallenge3 233
#define kCheat_ComboChallenge4 234
#define kCheat_ComboSidearm3 235
#define kCheat_ComboTravel2 236
#define kCheat_ComboTravel3 237
#define kCheat_ComboRandomStart 238
#define kCheat_ComboRandomAll 239
#define kCheat_ComboPrank 240
#define kCheat_GhostNinja 241
#define kCheat_TurboMode 242
#define kCheat_WeirdEconomy 243
#define kCheat_FarKnockers 244
#define kCheat_MaximumPuke 245
#define kCheat_GlassCannon 246
#define kCheat_SidearmChaos 247
#define kCheat_SuperHollower 248
#define kCheat_Feather 249
#define kCheat_NoRPG 250
#define kCheat_Ultimate 251
#define kCheat_TooMany 252
#define kCheat_ComboBacker 253

#define ENTITYTYPE_BASE 0
#define ENTITYTYPE_SPLINE_PROPS 1
#define ENTITYTYPE_INTERACT_PROPS 2
#define ENTITYTYPE_AGGRO_PROPS 3
#define ENTITYTYPE_ENEMY_PROPS 4
#define ENTITYTYPE_SURPRISE_SPAWN_PROPS 5
#define ENTITYTYPE_LAYER_OBJ 6
#define ENTITYTYPE_DISPENSER_PROPS 7
#define ENTITYTYPE_PLAYER 8
#define ENTITYTYPE_MARKER 9
#define ENTITYTYPE_SHIP_INTRO_BOSS 10
#define ENTITYTYPE_SHIP_INTRO_BOSS_CUTSCENE 11
#define ENTITYTYPE_SHIP_INTRO_BOSS_ARM 12
#define ENTITYTYPE_INTRO_BEACH_CUTSCENE 13
#define ENTITYTYPE_GOOPER_ENEMY 14
#define ENTITYTYPE_GOOPER_ENEMY_L2 15
#define ENTITYTYPE_GOOPERJUICE 16
#define ENTITYTYPE_GATOR_BOSS 17
#define ENTITYTYPE_GATOR_BODYPART_MID 18
#define ENTITYTYPE_GATOR_BODYPART_TAIL 19
#define ENTITYTYPE_SKULLKER_ENEMY 20
#define ENTITYTYPE_SKULLKER_ENEMY_L3 21
#define ENTITYTYPE_SKULLKER_ICE_SPIKE 22
#define ENTITYTYPE_SKULLKER_ICE_PROJECTILE 23
#define ENTITYTYPE_SKULLKER_FLAME_WAVE 24
#define ENTITYTYPE_BONEBIRD_ENEMY 25
#define ENTITYTYPE_BONEBIRD_ENEMY_L2 26
#define ENTITYTYPE_BIGFROG_ENEMY 27
#define ENTITYTYPE_WITCH_ENEMY 28
#define ENTITYTYPE_WITCH_PROJECTILE 29
#define ENTITYTYPE_PALADIN_ENEMY 30
#define ENTITYTYPE_PALADIN_ENEMY_L2 31
#define ENTITYTYPE_PALADIN_ENEMY_L3 32
#define ENTITYTYPE_PALADIN_BLADE_PROJ 33
#define ENTITYTYPE_PALADIN_FIRE_PROJ 34
#define ENTITYTYPE_SKIMMER_ENEMY 35
#define ENTITYTYPE_PICKUP 36
#define ENTITYTYPE_MOVING_PLATFORM 37
#define ENTITYTYPE_ANIM_EFFECT 38
#define ENTITYTYPE_ANIM_NUMBER 39
#define ENTITYTYPE_CLIMBING_ROPE 40
#define ENTITYTYPE_ROLLING_SPIKE 41
#define ENTITYTYPE_CRACKED_FLOOR 42
#define ENTITYTYPE_WEB_TILE 43
#define ENTITYTYPE_SPIDER_BUDDY 44
#define ENTITYTYPE_CONVEYOR_BELT 45
#define ENTITYTYPE_TIMED_PLATFORM 46
#define ENTITYTYPE_SECRET_PF_DIRT 47
#define ENTITYTYPE_ANIM_TILE 48
#define ENTITYTYPE_WEAPON_MERCHANT_ANIM_TILE 49
#define ENTITYTYPE_HEALING_WATER 50
#define ENTITYTYPE_BUSTER_PROJECTILE 51
#define ENTITYTYPE_FLOATING_AMMO 52
#define ENTITYTYPE_DAGGER_PROJECTILE 53
#define ENTITYTYPE_KNIFE_WEAPON 54
#define ENTITYTYPE_AXE_WEAPON 55
#define ENTITYTYPE_WARP_WEAPON 56
#define ENTITYTYPE_CLACKER_WEAPON 57
#define ENTITYTYPE_ROCK_WEAPON 58
#define ENTITYTYPE_BIGFROG_BUBBLE 59
#define ENTITYTYPE_AXE_SHOCKWAVE 60
#define ENTITYTYPE_DEATH_PIT_EFFECT 61
#define ENTITYTYPE_MAGIC_BUBBLE_EFFECT 62
#define ENTITYTYPE_MOVING_LAYER 63
#define ENTITYTYPE_WARPDOOR 64
#define ENTITYTYPE_SHORTCUT_PIPE 65
#define ENTITYTYPE_BURROW_CHECKPOINT 66
#define ENTITYTYPE_GEYSER_HOLE 67
#define ENTITYTYPE_BREAKABLE 68
#define ENTITYTYPE_CHEST 69
#define ENTITYTYPE_BARREL 70
#define ENTITYTYPE_STEAMPOOF 71
#define ENTITYTYPE_KEY_BLOCK 72
#define ENTITYTYPE_KEY_BLOCK_CHAIN 73
#define ENTITYTYPE_SPARK_DOOR 74
#define ENTITYTYPE_LAYER_AUTOSCROLL 75
#define ENTITYTYPE_CAM_AUTOSCROLLER 76
#define ENTITYTYPE_WEATHER_EFFECT 77
#define ENTITYTYPE_BG_PALETTE_LAYER_AREA 78
#define ENTITYTYPE_BRAMBLE_TILE 79
#define ENTITYTYPE_BRAMBLE_PLANT 80
#define ENTITYTYPE_JUG_BOTTLE 81
#define ENTITYTYPE_JUG_LOBBER 82
#define ENTITYTYPE_MERMAN 83
#define ENTITYTYPE_WATER_VALVE 84
#define ENTITYTYPE_WANDER_PROPS 85
#define ENTITYTYPE_WANDER_BOX 86
#define ENTITYTYPE_NPC 87
#define ENTITYTYPE_DUKE_NPC 88
#define ENTITYTYPE_INTERACTABLE 89
#define ENTITYTYPE_ANIM_EFFECT_EMITTER 90
#define ENTITYTYPE_AREA_MARKER 91
#define ENTITYTYPE_PANORAMA_MANAGER 92
#define ENTITYTYPE_PANORAMA_RECT 93
#define ENTITYTYPE_SPARK 94
#define ENTITYTYPE_SPARKREFILL 95
#define ENTITYTYPE_BURROW_WALL 96
#define ENTITYTYPE_WEATHER_RECT 97
#define ENTITYTYPE_BOAT 98
#define ENTITYTYPE_WARPROOM 99
#define ENTITYTYPE_VENT 100
#define ENTITYTYPE_SPIKE_TRAP 101
#define ENTITYTYPE_PRESSURE_PLATE 102
#define ENTITYTYPE_ARROW_TRAP 103
#define ENTITYTYPE_ARROW_TRAP_PROJ 104
#define ENTITYTYPE_BOSS_GATE 105
#define ENTITYTYPE_NECROMANCER_ENEMY 106
#define ENTITYTYPE_WORM_ENEMY 107
#define ENTITYTYPE_SPLIT_ENEMY 108
#define ENTITYTYPE_BOSS_FODDER 109
#define ENTITYTYPE_SHOCKTROOPER_ENEMY 110
#define ENTITYTYPE_SHOCKTROOPER_ENEMY_L3 111
#define ENTITYTYPE_SHOCKTROOPER_ENEMY_L4 112
#define ENTITYTYPE_SHOCK_SNIPER_BEAM 113
#define ENTITYTYPE_SHOCK_SNIPER_BEAM_PROJ 114
#define ENTITYTYPE_SHOCK_TROOPER_MINE 115
#define ENTITYTYPE_HULKTROOPER_ENEMY 116
#define ENTITYTYPE_HULKTROOPER_CHARGEPROJ 117
#define ENTITYTYPE_STOMPER_ENEMY 118
#define ENTITYTYPE_STOMPER_ENEMY_L2 119
#define ENTITYTYPE_STOMPER_STOMPPROJ 120
#define ENTITYTYPE_BOMBFLIER_ENEMY 121
#define ENTITYTYPE_BOMBFLIER_PROJ 122
#define ENTITYTYPE_BOMBFLIER_SPAWN_ZONE 123
#define ENTITYTYPE_MACETROOPER_ENEMY 124
#define ENTITYTYPE_MACETROOPER_ENEMY_L2 125
#define ENTITYTYPE_LOOTSKELETON_ENEMY 126
#define ENTITYTYPE_GATOR_LEAF 127
#define ENTITYTYPE_STATUE_HEAD 128
#define ENTITYTYPE_ROSE_AREA 129
#define ENTITYTYPE_ROSE_GROW_EXPANDER 130
#define ENTITYTYPE_ROSE_PLANT 131
#define ENTITYTYPE_BOSS_DEATH 132
#define ENTITYTYPE_BOSS_AREA 133
#define ENTITYTYPE_STATUE 134
#define ENTITYTYPE_SPIRIT_ENEMY 135
#define ENTITYTYPE_AGRO_AREA 136
#define ENTITYTYPE_STINKY_GUY 137
#define ENTITYTYPE_STINKY_GUY_FLY 138
#define ENTITYTYPE_EMPTY_GRAVE 139
#define ENTITYTYPE_INTERACT_ENTITY 140
#define ENTITYTYPE_TEST_TRAINING_DUMMY 141
#define ENTITYTYPE_DUCHESS_DOOR 142
#define ENTITYTYPE_PUMPKIN_FLIER 143
#define ENTITYTYPE_PUMPKIN_FLIER_PROJ 144
#define ENTITYTYPE_PUMPKIN_FLIER_SPAWN_ZONE 145
#define ENTITYTYPE_TOMB_LID 146
#define ENTITYTYPE_MANDRAKE_ENEMY 147
#define ENTITYTYPE_SPRING_BELLOWS 148
#define ENTITYTYPE_WIND_ROOM 149
#define ENTITYTYPE_THRESHER 150
#define ENTITYTYPE_RACCOON 151
#define ENTITYTYPE_BOAR 152
#define ENTITYTYPE_BOARJUICE 153
#define ENTITYTYPE_HUNTSMAN_ENEMY 154
#define ENTITYTYPE_OSSEX_CITIZEN_ENEMY_SCYTHE 155
#define ENTITYTYPE_OSSEX_CITIZEN_ENEMY_PITCHFORK 156
#define ENTITYTYPE_SCARECROW_NPC 157
#define ENTITYTYPE_LIGHTNING_ZONE 158
#define ENTITYTYPE_LIGHTNING_ROD 159
#define ENTITYTYPE_LIGHTNING 160
#define ENTITYTYPE_LIGHTNING_CRIT 161
#define ENTITYTYPE_LIGHTNING_PROJECTILE 162
#define ENTITYTYPE_DUCHESS_BOSS 163
#define ENTITYTYPE_LIVING_HOUSE 164
#define ENTITYTYPE_DUCHESS_BOSS_TENTACLE 165
#define ENTITYTYPE_DUCHESS_BOSS_HEAD 166
#define ENTITYTYPE_DUCHESS_BOSS_THRONE 167
#define ENTITYTYPE_BG_DISTORTION_LAYER_AREA 168
#define ENTITYTYPE_INTRO_CINEMATIC_ANIM 169
#define ENTITYTYPE_CHECKPOINT_CHEST 170
#define ENTITYTYPE_CHECKPOINT_MAP 171
#define ENTITYTYPE_PUMPKIN_HANDS_ENEMY 172
#define ENTITYTYPE_GIGA_PUMPKIN_BOSS 173
#define ENTITYTYPE_GIGA_PUMPKIN_BOSS_HAND 174
#define ENTITYTYPE_PUMPKIN_HANDS_BLOCK 175
#define ENTITYTYPE_PUMPKIN_HANDS_HINT 176
#define ENTITYTYPE_THORNE_NPC 177
#define ENTITYTYPE_LAYER_CLIP_BOX_AREA 178
#define ENTITYTYPE_NECROMANCER_ENEMY_REVIVE_PROJ 179
#define ENTITYTYPE_BONESTONE_MACHINE 180
#define ENTITYTYPE_LEAF_NPC 181
#define ENTITYTYPE_LEAF_FRIEND_NPC 182
#define ENTITYTYPE_PITCHFORK_WEAPON 183
#define ENTITYTYPE_TORCH_WEAPON 184
#define ENTITYTYPE_TORCH_PARTICLE 185
#define ENTITYTYPE_SICKLE_WEAPON 186
#define ENTITYTYPE_NPC_PASSERBY 187
#define ENTITYTYPE_NPC_PASSERBY_RECT 188
#define ENTITYTYPE_PIG_NPC 189
#define ENTITYTYPE_CAMPFIRE 190
#define ENTITYTYPE_CAMPFIRE_KID_NPC 191
#define ENTITYTYPE_CAMPFIRE_QUEST_STARTER 192
#define ENTITYTYPE_TONGUE_NPC 193
#define ENTITYTYPE_EYE_NPC 194
#define ENTITYTYPE_HAZARD_BLOCK 195
#define ENTITYTYPE_MIRROR_RECT 196
#define ENTITYTYPE_EYEBALL_TRAP 197
#define ENTITYTYPE_FLOATING_VIRUS 198
#define ENTITYTYPE_FLOATING_VIRUS_SPIKE 199
#define ENTITYTYPE_FLOATING_VIRUS_CLOUD 200
#define ENTITYTYPE_ANGLE_BOUNCER 201
#define ENTITYTYPE_EGG_SAC 202
#define ENTITYTYPE_EGG_SAC_GRUB 203
#define ENTITYTYPE_SINE_KNIFE 204
#define ENTITYTYPE_ENDLESS_SPAWN_ZONE_PROPS 205
#define ENTITYTYPE_KNIFE_SPAWN_ZONE 206
#define ENTITYTYPE_INFINITE_SPAWNER 207
#define ENTITYTYPE_WALL_CLINGER 208
#define ENTITYTYPE_WALL_CLINGER_PROJ 209
#define ENTITYTYPE_PUFFER_ENEMY 210
#define ENTITYTYPE_PUFFER_SPIKE 211
#define ENTITYTYPE_HANGING_HOOK 212
#define ENTITYTYPE_BONE_MINER_PICKAXE 213
#define ENTITYTYPE_BONE_MINER_ENEMY 214
#define ENTITYTYPE_WATER_BEAR_ENEMY 215
#define ENTITYTYPE_WATER_BEAR_WAVE 216
#define ENTITYTYPE_WATER_BEAR_SLAM 217
#define ENTITYTYPE_LEAF_PILE 218
#define ENTITYTYPE_WEATHER_DRIP_EFFECT 219
#define ENTITYTYPE_WEATHER_SPARK_EFFECT 220
#define ENTITYTYPE_HUB_FOUNTAIN 221
#define ENTITYTYPE_FIRE_TILE 222
#define ENTITYTYPE_FISHING_MANAGER 223
#define ENTITYTYPE_FISHING_BOBBER_PLAYER 224
#define ENTITYTYPE_FISHING_SHADOW 225
#define ENTITYTYPE_SUBWEAPON_CYCLER 226
#define ENTITYTYPE_JUMPDOWN_AREA 227
#define ENTITYTYPE_JUMPDOWN_PUSHOUT_AREA 228
#define ENTITYTYPE_AXE_BLOCKER 229
#define ENTITYTYPE_FISH_RAISER 230
#define ENTITYTYPE_SHALLOW_WATER_AREA 231
#define ENTITYTYPE_LADDER_BLOCKER 232
#define ENTITYTYPE_RESURRECTUR_EFFECT 233
#define ENTITYTYPE_BGM_CROSSFADE 234
#define ENTITYTYPE_DARKNESS_AREA 235
#define ENTITYTYPE_DARKNESS_LIGHT_AREA 236
#define ENTITYTYPE_DARKNESS_MONSTER_NPC 237
#define ENTITYTYPE_DARKNESS_MONSTER_FACE 238
#define ENTITYTYPE_ORGAN_BLOCKER 239
#define ENTITYTYPE_WEAPON_GET_EFFECT 240
#define ENTITYTYPE_BONE_BLOCK 241
#define ENTITYTYPE_BONE_DUST_TILE 242
#define ENTITYTYPE_OLDMANWATERBEAR_HAT 243
#define ENTITYTYPE_HEALING_VIAL_PACK_MACHINE 244
#define ENTITYTYPE_NEWSPAPER_STAND 245
#define ENTITYTYPE_SHOCK_FLINT_PROJ 246
#define ENTITYTYPE_OOZE_TRAIL_TILE 247
#define ENTITYTYPE_FLYING_TOTEM_WISP 248
#define ENTITYTYPE_FLYING_TOTEM_WISP_PROJ 249
#define ENTITYTYPE_FOLLOW_FLY 250
#define ENTITYTYPE_BURROW_PULSE_ATTACK 251
#define ENTITYTYPE_COMBO_NUMBER_EFFECT 252
#define ENTITYTYPE_DYNAMITE 253
#define ENTITYTYPE_BOTTLE_MESSAGE 254
#define ENTITYTYPE_FIRE_WALL 255
#define ENTITYTYPE_TENTACLE_GATE 256
#define ENTITYTYPE_BEEBAT_ENEMY 257
#define ENTITYTYPE_BEEBAT_ENEMY_L2 258
#define ENTITYTYPE_BEEBAT_SPAWN_ZONE 259
#define ENTITYTYPE_FURRY_WALKER_ENEMY 260
#define ENTITYTYPE_GREMLIN_ENEMY 261
#define ENTITYTYPE_GREMLIN_SPEAR 262
#define ENTITYTYPE_DRAGONFLY_ENEMY 263
#define ENTITYTYPE_MOLEMAN_ENEMY 264
#define ENTITYTYPE_MOLEMAN_PROJ 265
#define ENTITYTYPE_SWITCH_VEIN 266
#define ENTITYTYPE_BRAIN_BOSS 267
#define ENTITYTYPE_BRAIN_BOSS_BLOCKER 268
#define ENTITYTYPE_BRAIN_BOSS_CHAIN 269
#define ENTITYTYPE_BRAIN_BOSS_CAGE 270
#define ENTITYTYPE_BRAIN_BOSS_SPIKE 271
#define ENTITYTYPE_BRAIN_BOSS_SNAKE 272
#define ENTITYTYPE_BRAIN_BOSS_EYE 273
#define ENTITYTYPE_BRAIN_BOSS_RING 274
#define ENTITYTYPE_BRAIN_BOSS_BEAM 275
#define ENTITYTYPE_BRAIN_BOSS_GROUND_TEAR 276
#define ENTITYTYPE_BRAIN_BOSS_CRUSHER 277
#define ENTITYTYPE_BRAIN_BOSS_EYE_BOLT 278
#define ENTITYTYPE_GRIND_RAIL 280
#define ENTITYTYPE_GRIND_RAIL_JUNCTION 281
#define ENTITYTYPE_SNOW_BOULDER 282
#define ENTITYTYPE_BADRAT_ENEMY 283
#define ENTITYTYPE_BADRAT_PROJ 284
#define ENTITYTYPE_ICE_BLOCK 285
#define ENTITYTYPE_DOGAPEDE_ENEMY 286
#define ENTITYTYPE_SWITCH_LEVER 287
#define ENTITYTYPE_SNOWMAN_ENEMY 288
#define ENTITYTYPE_PHASE_CHANGER_ENEMY 289
#define ENTITYTYPE_PHASE_CHANGER_FLAME 290
#define ENTITYTYPE_LAYER_VISIBILITY_BOX_AREA 291
#define ENTITYTYPE_MIMIC_ENEMY 292
#define ENTITYTYPE_MIMIC_BONE 293
#define ENTITYTYPE_MINER_BOSS 294
#define ENTITYTYPE_MINER_BOSS_DIRT_PROJ 295
#define ENTITYTYPE_MINER_BOSS_FRACTAL_TILE 296
#define ENTITYTYPE_MINER_BOSS_PICKAXE 297
#define ENTITYTYPE_ENGINEER_BOSS 298
#define ENTITYTYPE_ENGINEER_BOSS_PORTAL 299
#define ENTITYTYPE_ENGINEER_BOSS_WRENCH 300
#define ENTITYTYPE_ENGINEER_BOSS_WHEEL 301
#define ENTITYTYPE_ENGINEER_BOSS_JUNK 302
#define ENTITYTYPE_ENGINEER_BOSS_HEAD 303
#define ENTITYTYPE_ENGINEER_BOSS_TRAIN 304
#define ENTITYTYPE_ENGINEER_BOSS_SMOKE 305
#define ENTITYTYPE_TRAINYARD_BELL 306
#define ENTITYTYPE_BIGART_MANAGER 307
#define ENTITYTYPE_RESPAWN_MARKER_AREA 308
#define ENTITYTYPE_GLASS_FLIPPER 309
#define ENTITYTYPE_STAR_SHOOTER_ENEMY 310
#define ENTITYTYPE_STAR_SHOOTER_PROJ 311
#define ENTITYTYPE_STAR_SPAWN_ZONE 312
#define ENTITYTYPE_LASER_BLOCK 313
#define ENTITYTYPE_COMET 314
#define ENTITYTYPE_SATURN_HEAD_ENEMY 315
#define ENTITYTYPE_SATURN_HEAD_PROJ 316
#define ENTITYTYPE_FLOATING_SPIKE 317
#define ENTITYTYPE_MINION_ENEMY 318
#define ENTITYTYPE_MINION_TETHER 319
#define ENTITYTYPE_LAB_TUBE 320
#define ENTITYTYPE_SUMMONER_ENEMY 321
#define ENTITYTYPE_SUMMONER_PROJ 322
#define ENTITYTYPE_SUMMONER_PARTICLE 323
#define ENTITYTYPE_SENTRY 324
#define ENTITYTYPE_SENTRY_PROJ 325
#define ENTITYTYPE_SWITCH_ORE 326
#define ENTITYTYPE_RAINBOW_PLATFORM_STATIC 327
#define ENTITYTYPE_RAINBOW_PLATFORM 328
#define ENTITYTYPE_FERRO_FLUID_ENEMY 329
#define ENTITYTYPE_BLACK_HOLE_PIT 330
#define ENTITYTYPE_ASTRAL_ROTATOR 331
#define ENTITYTYPE_CIRCULUR_PLATFORM 332
#define ENTITYTYPE_ASTRAL_CULTIST_ENEMY 333
#define ENTITYTYPE_ASTRAL_CULTISTS_SWARM 334
#define ENTITYTYPE_ASTRAL_CULTIST_BEAM 335
#define ENTITYTYPE_ASTRAL_CULTIST_RING_PROJ 336
#define ENTITYTYPE_ROTATION_RING_CHILD_PROPS 337
#define ENTITYTYPE_ROTATION_RING 338
#define ENTITYTYPE_PLANET_HAZARD 339
#define ENTITYTYPE_RADIAL_MULTI_SPAWNER 340
#define ENTITYTYPE_ULTIMA_KNIGHT_ENEMY 341
#define ENTITYTYPE_ULTIMA_KNIGHT_PLANET 342
#define ENTITYTYPE_ULTIMA_KNIGHT_SUPERNOVA 343
#define ENTITYTYPE_ULTIMA_KNIGHT_SWORD 344
#define ENTITYTYPE_SPARK_CAGE_ENCOUNTER 345
#define ENTITYTYPE_SPARK_CAGE_CARRYABLE 346
#define ENTITYTYPE_SPARK_CAGE_ABSORB_PROJ 347
#define ENTITYTYPE_SNAKE_ENEMY 348
#define ENTITYTYPE_SNAKE_ENEMY_L2 349
#define ENTITYTYPE_ABDUCTED_BOSS 350
#define ENTITYTYPE_ABDUCTED_SWIPE_PROJ 351
#define ENTITYTYPE_ABDUCTED_ELECTRIC_NODE 352
#define ENTITYTYPE_ABDUCTED_MINION_ENEMY 353
#define ENTITYTYPE_ABDUCTED_MINION_INTRO 354
#define ENTITYTYPE_ABDUCTED_FIRE_PROJ 355
#define ENTITYTYPE_CREATURE_IN_THE_ICE_BOSS 356
#define ENTITYTYPE_CREATURE_IN_ICE_PROJ 357
#define ENTITYTYPE_CREATURE_IN_ICE_CHUNK 358
#define ENTITYTYPE_BOMB 359
#define ENTITYTYPE_SPAWN_RANGE_AREA 360
#define ENTITYTYPE_BONE_SAVER 361
#define ENTITYTYPE_SWITCH_AREA 362
#define ENTITYTYPE_SHIELD_PROJECTILE 363
#define ENTITYTYPE_MOUSETRAP 364
#define ENTITYTYPE_FLIP_TILE 365
#define ENTITYTYPE_SLOW_FLIER_ENEMY 366
#define ENTITYTYPE_SLOW_FLIER_ENEMY_L2 367
#define ENTITYTYPE_SLOW_FLIER_SPAWN_ZONE 368
#define ENTITYTYPE_PORTRAIT_ENEMY 369
#define ENTITYTYPE_FOG_THROWER_PROJECTILE 370
#define ENTITYTYPE_FROG_BUCKET 371
#define ENTITYTYPE_LEASHED_PHANTOM_WEAPON 372
#define ENTITYTYPE_BREAKABLE_WINDOW 373
#define ENTITYTYPE_TOWER_ATTACHMENT_DEVICE 374
#define ENTITYTYPE_TOWER_SPOOL 375
#define ENTITYTYPE_TOWER_ROPE 376
#define ENTITYTYPE_TOWER_COG 377
#define ENTITYTYPE_TOWER_LETTER 378
#define ENTITYTYPE_TOWER_SCROLLING_BG 379
#define ENTITYTYPE_TOWER_SCROLLING_BG_LAYOUT_TILE 380
#define ENTITYTYPE_TOWER_BARRIER_WALL 381
#define ENTITYTYPE_SILHOUETTE_AREA 382
#define ENTITYTYPE_THORNE_BOSS 383
#define ENTITYTYPE_THORNE_ECHO 384
#define ENTITYTYPE_THORNE_MINE 385
#define ENTITYTYPE_THORNE_MISSILE 386
#define ENTITYTYPE_THORNE_TORNADO 387
#define ENTITYTYPE_THORNE_ARENA_HELPER 388
#define ENTITYTYPE_CRACK_ICE 389
#define ENTITYTYPE_CRACK_ICE_LIGHT 390
#define ENTITYTYPE_DAK_ACK_PROJ 391
#define ENTITYTYPE_DAK 392
#define ENTITYTYPE_ACK 393
#define ENTITYTYPE_DUGIN_BOSS 394
#define ENTITYTYPE_LIONEL_NPC 395
#define ENTITYTYPE_LIONEL_VIAL 396
#define ENTITYTYPE_LIONEL_BOSS 397
#define ENTITYTYPE_LIONEL_PAPERS 398
#define ENTITYTYPE_LIONEL_FIREPLACE 399
#define ENTITYTYPE_LIONEL_ELECTRIC_PROJ 400
#define ENTITYTYPE_LIONEL_ELECTRIC_LASER 401
#define ENTITYTYPE_LIONEL_BOSS_ARENA_HELPER 402
#define ENTITYTYPE_ELECTRIC_FLOOR_EFFECT 403
#define ENTITYTYPE_GUARD_NPC 404
#define ENTITYTYPE_MOON_BOSS 405
#define ENTITYTYPE_MOON_BOSS_PROJ 406
#define ENTITYTYPE_MAID_NPC 407
#define ENTITYTYPE_MURIEL_NPC 408
#define ENTITYTYPE_UNDERLAB_UPGRADER_NPC 409
#define ENTITYTYPE_HAUNTED_URN_GHOST 410
#define ENTITYTYPE_MAXI_BOSS 411
#define ENTITYTYPE_MAXI_PROJ 412
#define ENTITYTYPE_MACE_OBJECT 413
#define ENTITYTYPE_CLOWN_NPC 414
#define ENTITYTYPE_BARRIER_PARASOL 415
#define ENTITYTYPE_BARD_BOSS 416
#define ENTITYTYPE_BARD_PROJECTILE 417
#define ENTITYTYPE_BARD_SPOTLIGHT 418
#define ENTITYTYPE_BUTLER_BOSS 419
#define ENTITYTYPE_BUTLER_FURBALL 420
#define ENTITYTYPE_BUTLER_NECK 421
#define ENTITYTYPE_BUTLER_PIECE 422
#define ENTITYTYPE_DISTANT_TOWER_ANIM_TILE 423
#define ENTITYTYPE_LAVA_TRENCH_TILE 424
#define ENTITYTYPE_WEAPON_BROTHER_BOSS 425
#define ENTITYTYPE_WEAPON_BROTHER_PROJ 426
#define ENTITYTYPE_WEAPON_BROTHER_ANVIL 427
#define ENTITYTYPE_HITTABLE_SIGN 428
#define ENTITYTYPE_EVRA_BOSS 429
#define ENTITYTYPE_EVRA_SKELETON 430
#define ENTITYTYPE_EVRA_BODY 431
#define ENTITYTYPE_EVRA_ORB 432
#define ENTITYTYPE_SNOWBALL_ENJOYER_SNOWMAN 433
#define ENTITYTYPE_LONG_NOSE_NPC 434
#define ENTITYTYPE_LONG_NOSE_LIMIT_AREA 435
#define ENTITYTYPE_FLOWER_POT 436
#define ENTITYTYPE_BOUQUET 437
#define ENTITYTYPE_NOSE_GIRL_NPC 438
#define ENTITYTYPE_TAVERN_MUSIC_MANAGER 439
#define ENTITYTYPE_GIGA_THORNE_BOSS 440
#define ENTITYTYPE_GIGA_THORNE_TRIDENT 441
#define ENTITYTYPE_MOTH_BOSS 442
#define ENTITYTYPE_MOTH_BOSS_PROJ 443
#define ENTITYTYPE_BRAINLESS_BRAIN 444
#define ENTITYTYPE_KITE 445
#define ENTITYTYPE_GHOST_REFLECTION 446
#define ENTITYTYPE_GHOST_REFLECTION_STOOL 447
#define ENTITYTYPE_DINNER_CUTSCENE 448
#define ENTITYTYPE_DINNER_CHAIR 449
#define ENTITYTYPE_CAT_GHOST 450
#define ENTITYTYPE_TICKET_MACHINE 451
#define ENTITYTYPE_TRAIN_MANAGER 452
#define ENTITYTYPE_TRAIN_AUTHORITY 453
#define ENTITYTYPE_TRAIN_CONDUCTOR 454
#define ENTITYTYPE_TRAIN_ANIM 455
#define ENTITYTYPE_SHIP_INTRO_BOSS_TRINKET_SPAWNER 456
#define ENTITYTYPE_ARTIFACT_SEEKER 457
#define ENTITYTYPE_ARTIFACT_SEEKER_BACKPACK 458
#define ENTITYTYPE_ARTIFACT_SEEKER_TRINKET 459
#define ENTITYTYPE_TAILOR_CURTAIN 460
#define ENTITYTYPE_JOULE_ALEMBIC 461
#define ENTITYTYPE_SIDEARM_SAVER 462
#define ENTITYTYPE_TRAINING_DUMMY 463
#define ENTITYTYPE_CHECKPOINT_THEME_MANAGER 464
#define ENTITYTYPE_PHONOGRAPH 465
#define ENTITYTYPE_WRECKER 466
#define ENTITYTYPE_RING_MASTER_NPC 467
#define ENTITYTYPE_MINIGAME_RING 468
#define ENTITYTYPE_WRECKER_STEAM 469
#define ENTITYTYPE_NEW_SHOP_SIGN 470
#define ENTITYTYPE_BOUNCE_PLANT 471
#define ENTITYTYPE_KEY_REWARD 472
#define ENTITYTYPE_CREDITS_BIRD 473
#define ENTITYTYPE_PLUS_SECOND_EFFECT 474
#define ENTITYTYPE_PUPPET_MASTER_NPC 475
#define ENTITYTYPE_PUPPET_MASTER_HOLE 476
#define ENTITYTYPE_PUPPET_MASTER_DOLL 477
#define ENTITYTYPE_PUPPET_MASTER_WISP 478
#define ENTITYTYPE_GIGA_LIONEL_BOSS 479
#define ENTITYTYPE_GIGA_LIONEL_CRYSTAL 480
#define ENTITYTYPE_GIGA_LIONEL_CRYSTAL_SHARD 481
#define ENTITYTYPE_GIGA_LIONEL_ARM 482
#define ENTITYTYPE_GIGA_LIONEL_BEAM_PROJ 483
#define ENTITYTYPE_TOWER_CLIMB_CLOUD 484
#define ENTITYTYPE_GIGA_THORNE_NPC 485
#define ENTITYTYPE_BIRD 486
#define ENTITYTYPE_TAVERN_THEME_MANAGER 487
#define ENTITYTYPE_TAVERN_ANIM_TILE 488
#define ENTITYTYPE_FLYBY_GENERIC_OBJECT 489
#define ENTITYTYPE_FISHING_BOBBER 490
#define ENTITYTYPE_LIONEL_PORTRAIT 491
#define ENTITYTYPE_MOTH_NPC 492
#define ENTITYTYPE_METEOR_FALL 493
#define ENTITYTYPE_VIAL_SALVO_PROJ 494
#define ENTITYTYPE_RUSH_PLATFORM 495
#define ENTITYTYPE_FIERY_STONE_PROJ 496
#define ENTITYTYPE_BONE_BEACH_MONSTER_LAYER 497
#define ENTITYTYPE_PROXIMITY_DISPLACER_RECT 498
#define ENTITYTYPE_FISHING_ENTITY 499
#define ENTITYTYPE_FISH_BOSS 500
#define ENTITYTYPE_FISHING_PROJ 501
#define ENTITYTYPE_FISHING_RAFT 502
#define ENTITYTYPE_KICKCAN 503
#define ENTITYTYPE_HITTABLE_ANIM_TILE 504
#define ENTITYTYPE_FISH_BOSS_PROJ 505
#define ENTITYTYPE_FISH_TACKLE_BOX 506
#define ENTITYTYPE_VIAL_DECOY 507
#define ENTITYTYPE_VIAL_PARRY_PROJ 508
#define ENTITYTYPE_TOWER_KILL_LINE 509
#define ENTITYTYPE_MIRROR_NPC 510
#define ENTITYTYPE_BASEMENT_SECRET 511
#define ENTITYTYPE_LIONEL_CREDITS_BOAT 512
#define ENTITYTYPE_PROVISIONER_GRAB 513
#define ENTITYTYPE_BEAST_FIREBALL 514
#define ENTITYTYPE_PIT_MARKER 515
#define ENTITYTYPE_REDFROG_NPC 516
#define ENTITYTYPE_ROOM_SAVE_MARKER 517
#define ENTITYTYPE_GOOD_DEED_INDICATOR 518
#define ENTITYTYPE_FISH_AREA_INFO 519
#define ENTITYTYPE_SPECIAL_COLLISION 520
#define ENTITYTYPE_MOON_ANIM 521
#define ENTITYTYPE_LAYER_LAUNCHER 522
#define ENTITYTYPE_GUT_DEPTHS_RESPAWN_HANDLER 523
#define ENTITYTYPE_CALCIUM_HOLE_ANIM_TILE 524
#define ENTITYTYPE_ENGINEER_WHEEL_ANIM_TILE 525
#define ENTITYTYPE_SHADOW_ELEVATOR 526

#define kSparkType_None 0
#define kSparkType_Enemy 1
#define kSparkType_Loc 2
#define kSparkType_Door 3
#define kSparkType_Count 4

#define kGameAct_DpadLeft 0
#define kGameAct_DpadRight 1
#define kGameAct_DpadUp 2
#define kGameAct_DpadDown 3
#define kGameAct_AttackA 4
#define kGameAct_HealB 5
#define kGameAct_SubweaponC 6
#define kGameAct_Jump 7
#define kGameAct_L 8
#define kGameAct_R 9
#define kGameAct_Start 10
#define kGameAct_Select 11
#define kGameAct_L2 12
#define kGameAct_R2 13
#define kGameAct_Count 14

#define kTileLevel2EntitySpawnType_Infinite 0
#define kTileLevel2EntitySpawnType_PersistentA 1
#define kTileLevel2EntitySpawnType_Persistent 2
#define kTileLevel2EntitySpawnType_Room 3
#define kTileLevel2EntitySpawnType_RoomTransition 4
#define kTileLevel2EntitySpawnType_RoomTransitionInfinite 5
#define kTileLevel2EntitySpawnType_RoomViewInfinite 6
#define kTileLevel2EntitySpawnType_Contents 7
#define kTileLevel2EntitySpawnType_Child 8
#define kTileLevel2EntitySpawnType_RoomInfinite 9
#define kTileLevel2EntitySpawnType_RangeEnter 10
#define kTileLevel2EntitySpawnType_RangeExit 11
#define kTileLevel2EntitySpawnType_Present 12
#define kTileLevel2EntitySpawnType_Disable 13
#define kTileLevel2EntitySpawnType_SpawnChildren 14
#define kTileLevel2GeometryFlag_None 0
#define kTileLevel2GeometryFlag_NoDiagonal 1
#define kTileLevel2EntityShapeType_Tile 0
#define kTileLevel2EntityShapeType_Rect 1
#define kTileLevel2EntityShapeType_Spline 2
